name: in_memory_todos_data_source
description: An in-memory implementation of the TodosDataSource interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  todos_data_source:
    path: ../todos_data_source
  uuid: ^4.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.25.0
  very_good_analysis: ^7.0.0
