name: kitchen_sink
description: A kitchen sink example with Dart Frog.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^0.3.0

dev_dependencies:
  http: ^1.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
