name: example
description: An example application built with dart_frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dart_frog:
    path: ../packages/dart_frog

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
