name: example
description: An example application built with dart_frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog:
    git:
      url: https://github.com/VeryGoodOpenSource/dart_frog
      path: packages/dart_frog

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^3.0.0

dependency_overrides:
  dart_frog:
    path: ../packages/dart_frog
