version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/bricks/create_dart_frog/hooks"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/bricks/dart_frog_dev_server/hooks"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/bricks/dart_frog_prod_server/hooks"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/echo"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/hello_world"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/web_socket_counter"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/counter"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/todos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/todos/packages/todos_data_source"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/todos/packages/in_memory_todos_data_source"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/examples/kitchen_sink"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/dart_frog_cli"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/dart_frog_cli/e2e"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/dart_frog_gen"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/dart_frog"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/dart_frog_web_socket"
    schedule:
      interval: "daily"