name: dart_frog_gen
description: Code generation tooling for dart_frog
version: 0.0.1-dev.1
homepage: https://github.com/VeryGoodOpenSource/dart_frog

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  path: ^1.8.1

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
