name: dart_frog_gen
description: Code generation tooling for Dart Frog. Built by Very Good Ventures.
version: 0.3.2
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  path: ^1.8.1
  pubspec_parse: ^1.2.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
