name: dart_frog_gen
description: Code generation tooling for Dart Frog. Built by Very Good Ventures.
version: 2.0.0
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview
topics: [server, backend, dart-frog, codegen]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  path: ^1.8.1
  pubspec_parse: ^1.2.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ">=5.1.0 <8.0.0"
