name: dart_frog_auth
description: Header authentication based middlewares for Dart Frog. Built by Very Good Ventures.
version: 0.1.0
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^0.3.6

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
