name: dart_frog_cli
description: The official command line interface for Dart Frog. Built by Very Good Ventures.
version: 0.3.5
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  args: ^2.1.0
  cli_completion: ^0.3.0
  mason: ^0.1.0-dev.39
  meta: ^1.7.0
  path: ^1.8.1
  pub_updater: ">=0.2.4 <0.4.0"
  pubspec_parse: ^1.2.0
  stream_transform: ^2.0.0
  watcher: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

executables:
  dart_frog:
