name: dart_frog_cli
description: The official command line interface for Dart Frog. Built by Very Good Ventures.
version: 1.2.3
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview
topics: [server, backend, shelf, dart-frog, cli]

screenshots:
  - description: 'Dart Frog logo.'
    path: assets/logo.png

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  dart_frog_gen: ^2.0.0
  equatable: ^2.0.5
  mason: 0.1.0
  meta: ^1.15.0
  path: ^1.9.0
  pub_updater: ^0.5.0
  pubspec_parse: ^1.3.0
  stream_transform: ^2.1.0
  uuid: ^4.4.2
  watcher: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  dart_frog:
