name: dart_frog_cli
description: The official command line interface for dart_frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  args: ^2.1.0
  mason: ^0.1.0-dev.19
  meta: ^1.7.0
  path: ^1.8.1
  watcher: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

executables:
  dart_frog: