name: dart_frog_web_socket
description: WebSocket support for Dart Frog. Built by Very Good Ventures.
version: 1.0.0
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview
topics: [server, backend, dart-frog, websocket]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  shelf_web_socket: ">=1.0.3 <3.0.0"
  web_socket_channel: ">=2.0.0 <4.0.0"

dev_dependencies:
  http: ^1.0.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ">=5.1.0 <8.0.0"
