name: dart_frog_web_socket
description: WebSocket support for Dart Frog. Built by Very Good Ventures.
version: 0.1.0-dev.2
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  shelf_web_socket: ^1.0.3
  web_socket_channel: ^2.0.0

dev_dependencies:
  http: ^0.13.5
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ">=3.1.0 <5.0.0"
