name: hello_world
description: A hello world example app built with Dart Frog.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0

dev_dependencies:
  http: ^1.0.0
  mocktail: ^1.0.0
  test: ^1.25.0
  very_good_analysis: ^7.0.0
