name: hello_world
description: A hello world example app built with Dart Frog.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0

dev_dependencies:
  http: ^0.13.5
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1
