name: dart_frog_dev_server_hooks
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog_gen: ^2.0.0
  mason: ^0.1.0-dev.39
  pubspec_parse: ^1.2.0

dev_dependencies:
  mocktail: ^1.0.0
  path: ^1.8.2
  test: ^1.25.0
  very_good_analysis: ^7.0.0
