name: kitchen_sink_client
description: The  Dart Client
version: 1.0.0+1s
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  http: ^0.13.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
