name: dart_frog_cli_e2e
description: End to End tests for package:dart_frog_cli
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  dart_frog:
    path: ../../dart_frog
  http: ^0.13.4
  meta: ^1.7.0
  path: ^1.8.2
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1
