name: dart_frog_prod_server_hooks
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog_gen: ^2.0.0
  equatable: ^2.0.5
  io: ^1.0.3
  mason: ^0.1.0-dev.39
  path: ^1.8.1
  yaml: ^3.1.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.25.0
  very_good_analysis: ^7.0.0
