name: dart_frog_prod_server_hooks
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog_gen: ^0.3.0
  io: ^1.0.3
  mason: ^0.1.0-dev.39
  path: ^1.8.1
  pubspec_parse: ^1.2.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1
