name: dart_frog_prod_server_hooks
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_frog_gen: ^0.0.2-dev.1
  mason: ">=0.1.0-dev <0.1.0"
  path: ^1.8.1
  pubspec_parse: ^1.2.0
