name: create_dart_frog_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mason: ^0.1.0-dev.31
  path: ^1.8.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
