name: create_dart_frog_hooks

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.39
  path: ^1.8.1

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.25.0
  very_good_analysis: ^7.0.0
