name: create_dart_frog_hooks

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  mason: ^0.1.0-dev.39
  path: ^1.8.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1
