name: dart_frog
description: A fast, minimalistic backend framework for Dart built by Very Good Ventures.
version: 0.3.6
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview

environment:
  sdk: ">=3.0.0-0 <3.0.0"

dependencies:
  http_methods: ^1.1.0
  http_parser: ^4.0.2
  meta: ^1.9.0
  mime: ^1.0.4
  shelf: ^1.4.0
  shelf_hotreload: ^1.3.0
  shelf_static: ^1.1.1

dev_dependencies:
  http: ^0.13.4
  mocktail: ^0.3.0
  path: ^1.8.2
  test: ^1.19.2
  very_good_analysis: ^4.0.0

false_secrets:
  - test/src/serve_test.dart
