name: dart_frog
description: A fast, minimalistic backend framework for Dart built by Very Good Ventures.
version: 1.2.0
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview
topics: [server, backend, shelf, dart-frog]

screenshots:
  - description: 'Dart Frog logo.'
    path: assets/logo.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http_methods: ^1.1.0
  http_parser: ^4.0.2
  meta: ^1.9.0
  mime: ">=1.0.4 <3.0.0"
  shelf: ^1.4.0
  shelf_hotreload: ^1.3.0
  shelf_static: ^1.1.1

dev_dependencies:
  http: ^1.0.0
  mocktail: ^1.0.0
  path: ^1.8.2
  test: ^1.19.2
  very_good_analysis: ">=5.1.0 <8.0.0"

false_secrets:
  - test/src/serve_test.dart
