name: dart_frog
description: A fast, minimalistic backend framework for Dart built by Very Good Ventures.
version: 0.3.2
homepage: https://dartfrog.vgv.dev
repository: https://github.com/VeryGoodOpenSource/dart_frog
issue_tracker: https://github.com/VeryGoodOpenSource/dart_frog/issues
documentation: https://dartfrog.vgv.dev/docs/overview

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http_methods: ^1.1.0
  shelf: ^1.4.0
  shelf_hotreload: ^1.3.0
  shelf_static: ^1.1.1

dev_dependencies:
  http: ^0.13.4
  mocktail: ^0.3.0
  path: ^1.8.2
  test: ^1.19.2
  very_good_analysis: ">=3.1.0 <5.0.0"
