name: web_socket_counter
description: An example counter app built with Dart Frog using WebSockets.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.1
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  http: ^1.2.1
  mocktail: ^1.0.0
  test: ^1.25.0
  very_good_analysis: ^7.0.0
  web_socket_client: ^0.1.0-dev.1
