name: dart_frog_test
description: Testing helpers for Dart Frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
