name: Docker Tests

on:
  workflow_call:
    inputs:
      setup:
        required: false
        type: string
        default: ""
      docker_directory:
        required: false
        type: string
        default: "build"
      test_directory:
        required: false
        type: string
        default: "e2e"
      working_directory:
        required: false
        type: string
        default: "."

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: âš™ï¸ Run Setup
        if: "${{inputs.setup != ''}}"
        run: ${{inputs.setup}}

      - name: ğŸ“¦ Install Dependencies
        run: dart pub get

      - name: ğŸ¸ Dart Frog Build
        run: dart_frog build

      - name: ğŸ³ Build Docker Image
        run: docker build -q ${{inputs.docker_directory}} -t e2e-image

      - name: âš¡ï¸ Run Docker Image
        run: docker run -d -p 8080:8080 --name e2e --rm e2e-image

      - name: ğŸ§ª Run Docker Tests
        run: dart test ${{inputs.test_directory}}

      - name: ğŸ§¹ Docker Cleanup
        if: success() || failure()
        run: |
          docker stop e2e
          docker image rm e2e-image
