name: dart_frog_vscode

on:
  pull_request:
    paths:
      - ".github/workflows/dart_frog_vscode.yaml"
      - "extensions/vscode/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/dart_frog_vscode.yaml"
      - "extensions/vscode/**"

jobs:
  build:
    defaults:
      run:
        working-directory: extensions/vscode

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ğŸ¯ Setup Node.js (18.16.1)
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ•µï¸ Analyze
        run: npm run lint

      - name: ğŸ§ª Run tests
        run: npm test

      - name: ğŸ“Š Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: extensions/vscode/coverage/lcov.info
