name: publish

on:
  push:
    tags:
      - '*-v*.*.*'

jobs:
  to_publish:
    if: false
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    outputs:
      package: ${{ steps.package.outputs.package }}
      brick: ${{ steps.brick.outputs.brick }}
      extension: ${{ steps.extension.outputs.extension }}

    steps:
      - name: ðŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: ðŸ“¦ Finding a package to publish
        id: package
        run: |
          tag=${GITHUB_REF#refs/*/}
          package=$(echo $tag | sed -En "s/^(.*)-v(.*)/\1/p")
          if [[ -d "packages/$package" ]]; then
            echo "::set-output name=package::${package}"
          fi

      - name: ðŸ§± Finding a brick to publish
        id: brick
        if: steps.package.outputs.package == ''
        run: |
          tag=${GITHUB_REF#refs/*/}
          brick=$(echo $tag | sed -En "s/^(.*)-v(.*)/\1/p")
          if [[ -d "bricks/$brick" ]]; then
            echo "::set-output name=brick::${brick}"
          fi

      - name: ðŸ’» Finding an extension to publish
        id: extension
        if: steps.package.outputs.package == '' && steps.brick.outputs.brick == ''
        run: |
          tag=${GITHUB_REF#refs/*/}
          extension=$(echo $tag | sed -En "s/^(.*)-v(.*)/\1/p")
          if [[ -d "extensions/$extension" ]]; then
            echo "::set-output name=extension::${extension}"
          fi

  failed_to_find:
    needs: to_publish
    if: needs.to_publish.outputs.package == '' && needs.to_publish.outputs.brick == '' && needs.to_publish.outputs.extension == ''
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ˜¢ No package or brick found to publish
        run: exit 1

  publish_package:
    needs: to_publish
    if: needs.to_publish.outputs.package != ''

    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_pub_publish.yml@v1
    with:
      working_directory: packages/${{ needs.to_publish.outputs.package }}
      pub_credentials: secrets.PUB_CREDENTIALS

  publish_brick:
    needs: to_publish
    if: needs.to_publish.outputs.brick != ''

    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/mason_publish.yml@v1
    with:
      working_directory: bricks/${{ needs.to_publish.outputs.brick }}
      mason_credentials: secrets.MASON_CREDENTIALS

  publish_extension:
    needs: to_publish
    if: needs.to_publish.outputs.extension != ''

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: extensions/${{ needs.to_publish.outputs.extension }}

    steps:
      - name: ðŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts

      - name: ðŸŽ‰ Publish VS Code Extension
        if: needs.to_publish.outputs.extension == 'vscode'
        run: |
          npm install -g @vscode/vsce 

          echo "${{ secrets.VSCODE_CREDENTIALS }}" > vscode-credentials
          vsce login VeryGoodVentures < vscode-credentials

          tag=${GITHUB_REF#refs/*/}
          version=$(echo $tag | sed -En "s/^(.*)-v(.*)/\2/p")
          vsce publish "${version}" --no-update-package-json
